### ISSUE TITLE
why some code are commented in configure

### ISSUE THREAD

**Issue by unicornx** [riscv-android-src/platform-external-qemu#6]
in `./configure`, following code lines are commented.
```
#if test "$mingw32" == "yes" ; then
#    WINVER=0x0600
#    QEMU_CFLAGS="-DWINVER=$WINVER -D_WIN32_WINNT=$WINVER $QEMU_CFLAGS"
#fi
```
Why we comment them?

I think it is not needed, we should revert it back to original code.
I reverted and tested building and run, looks good.

**Comment by Lifang-XIA** [comment]
It may get some error from the env. It must be a workaround.
Please Go ahead.

**Comment by unicornx** [comment]
closed with https://github.com/riscv-android-src/platform-external-qemu/pull/7
